//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityKeys
    {
        public int KeyID { get; set; }
        public string Key { get; set; }
        public int UserID { get; set; }
        public System.DateTime Expire { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
